workflows:
  ios-project-debug:
    name: iOS debug
    environment:
      xcode: 15.0.0
      cocoapods: default
      vars:
          XCODE_PROJECT: "saranggame.xcodeproj"
          XCODE_SCHEME: "saranggame"
    scripts:
      - name: List available simulators
        script: |
          xcrun simctl list devices
      - name: Run tests
        script: |
          xcodebuild \
          -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0' \
          clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - name: Build debug app
        script: |
          xcodebuild build -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - muhammadwafa105@gmail.com
